<?php
/*
    We're using require_once here because we want to:
    1. Only include the file once
    2. Show us a FATAL ERROR if missing or we've linked the file incorrectly

    Other ways to include files are available:
    include(); - include files multiple times, only warning if missing
    require(); - include file multiple times, FATAL ERROR if missing
    include_once(); - include file ONLY once, only warning if missing

    Adding the _once multiple times just means any future _once of the
    same file gets ignored.

    So:
    require_once('assets/inc/header.php');
    require_once('assets/inc/header.php');
    require_once('assets/inc/header.php');

    Only the first one is loaded, and the others are ignored.
*/

require_once('assets/inc/header.php');
?>

<div class="background">
                <div class="row">
                    <div class="col-8">
                        <div class="content">
                        <img src="../assets/img/mercury-b.jpg" alt="Mercury Planet"/>
                        <h1>Mercury's Subtle Colors</h1>
                        <p>TMESSENGER's Wide Angle Camera (WAC), part of the Mercury Dual Imaging System (MDIS), is equipped with 11 narrow-band color filters. As the spacecraft receded from Mercury after making its closest approach on 14 January 2008, the WAC recorded a 3x3 mosaic covering part of the planet not previously seen by spacecraft. The color image shown here was generated by combining the mosaics taken through the WAC filters that transmit light at wavelengths of 1000 nm (infrared), 700 nm (far red), and 430 nm (violet).</p><a  class="button" href="mercury-details.php">Details</a>
                    </div><!-- content -->
                    </div><!-- col9 -->

                    <div class="col-4">
                        <div class="side-bar">
                            <ul>
                                <li><a href="mercury-gallery-1.php"><img src="./assets/img/mercury-side-a.jpg" alt="Mercury Planet 1"></a></li>
                                <li><a href="mercury-gallery-2.php"><img src="./assets/img/mercury-side-b.jpg" alt="Mercury Planet 2"></a></li>
                                <li><a href="mercury-gallery-3.php"><img src="./assets/img/mercury-side-c.jpg" alt="Mercury Planet 3"></a></li>
                                <li><a href="mercury-gallery-4.php"><img src="./assets/img/mercury-side-d.jpg" alt="Mercury Planet 4"></a></li>
                            </ul>
                        </div><!-- side-bar-->
                    </div><!-- col3 -->
                </div><!-- row -->
</div><!-- background -->


<?php require_once('assets/inc/footer.php') ?>
